pipeline {
    
    agent any

    tools{
        maven "maven-3.6.1"
    }

    stages {
        stage('build') {
            steps {
                echo 'compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Runnign units tests on worker app'
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
            }
        }
    }
    
    post {
        always{
            echo 'worker pipeline is completed'
        }
    }
}
