pipeline {
    
    agent any

    tools{
        maven "maven-3.6.1"
    }

    stages {
        stage('build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Runnign units tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch = 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always{
            echo 'worker app pipeline is completed'
        }
    }
}
